apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
  - image: alpine:3.20
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: IfNotPresent
    name: alpine
    resources:
      requests: 
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "2"
        cpu: "2Gi"
  restartPolicy: Always