apiVersion: v1
kind: Pod
metadata:
  name: python
spec:
  containers:
  - name: python
    image: python
    command:
      - pyhton
      - "-c"
      - "import time; time.sleep(10); exit(1)"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
